version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev

db:
  build:
    image: "db Image"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: DBNAME
      MYSQL_USER: DBNAME
      MYSQL_PASSWORD: DBNAME


keycloak:
  container_name: keycloak
  image: jboss/keycloak:13.0.0
  restart: always
  volumes:
      - "volume Link"
  ports:
      - "8080:8080"
  environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
      DB_VENDOR: mysql
      KEYCLOAK_IMPORT: /tmp/realm-export.json

