version: '3'
services:

    keycloak:
        container_name: keycloak
        image: jboss/keycloak:13.0.0
        restart: always
        volumes:
            - "./realm-export.json:/tmp/realm-export.json"
        ports:
            - "8080:8080"
        environment:
            KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
            KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
            DB_VENDOR: H2 //Custom DB
            KEYCLOAK_IMPORT: /tmp/realm-export.json

    react-app:
        container_name: react-app
        image: 409255/frontend
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "80:80"
        depends_on:
            - keycloak