# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker serie builds

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mohammad1996/react
        always_pull: true
        build_args: arg1=value1,arg2=value2
        cache_froms: mohammad1996/react:latest
        tags: latest
